title: Chingay 2024
url: https://www.chingay.gov.sg
favicon: /images/favicon.ico
colors:
  primary-color: "#053d60"
  secondary-color: "#b242a2"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#eac0f3"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
resources_name: Resources
description: Chingay Parade Singapore
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.dhbyir1x3qc27.amplifyapp.com/
prod: https://master.dhbyir1x3qc27.amplifyapp.com/
is_government: true
google_analytics: UA-28012022-1
facebook-pixel: ""
linkedin-insights: ""
shareicon: /images/isomer-logo.svg
google_analytics_ga4: ""
